/**
 * Vibe Detector Heuristics
 * Analisa o DOM e o CSS para identificar padrões comuns de sites gerados por IA.
 */

export interface VibeResult {
  score: number; // 0-100
  factors: {
    name: string;
    description: string;
    weight: number;
    detected: boolean;
  }[];
}

export function analyzeVibe(doc: Document): VibeResult {
  const factors = [
    {
      name: "Tailwind & Utility DNA",
      description: "Massive utility class patterns typical of v0, Lovable, and Bolt.",
      weight: 15,
      detected: false,
    },
    {
      name: "Shadcn/UI & Radix",
      description: "Radix component structures and standard Shadcn classes.",
      weight: 15,
      detected: false,
    },
    {
      name: "AI Iconography (Lucide)",
      description: "Heavy use of Lucide Icons, the AI industry standard.",
      weight: 10,
      detected: false,
    },
    {
      name: "Vibe Coding Stack",
      description: "Combined use of Framer Motion, Lucide, and Tailwind.",
      weight: 15,
      detected: false,
    },
    {
      name: "AI IDE & Agent Markers",
      description: "Signatures from Cursor, Windsurf, Trae, Replit, or Devin.",
      weight: 25,
      detected: false,
    },
    {
      name: "Platform Signatures",
      description: "Markers from Google AI Studio, Lovable, v0, or Bolt.new.",
      weight: 20,
      detected: false,
    },
  ];
    // --- Advanced Heuristics ---
    factors.push(
      {
        name: "Prompt Artifact Comments",
        description: "Comments or metadata referencing prompts, e.g., 'Prompt: ...' or 'Generated by ...'",
        weight: 7,
        detected: false,
      },
      {
        name: "Model/Provider Metadata",
        description: "References to OpenAI, Anthropic, Google, or license headers auto-inserted by AI platforms.",
        weight: 7,
        detected: false,
      },
      {
        name: "Generic Code Structure",
        description: "Unusual file/folder names, placeholder text, or overly generic function/variable names.",
        weight: 6,
        detected: false,
      },
      {
        name: "AI SDK/Dependency Clues",
        description: "Presence of AI SDKs or dependencies in the codebase (e.g., openai, langchain, gpt-engineer).",
        weight: 6,
        detected: false,
      },
      {
        name: "Commit/PR Metadata",
        description: "Commit messages or PR descriptions referencing AI tools or prompt-based workflows.",
        weight: 5,
        detected: false,
      },
      {
        name: "Default AI UI Patterns",
        description: "Default layouts or icon sets popular with AI tools (e.g., Bento Grid, Lucide, Tabler).",
        weight: 5,
        detected: false,
      },
      {
        name: "English-Only Comments",
        description: "All comments and docs in English, even in non-English projects.",
        weight: 4,
        detected: false,
      },
      {
        name: "Consistent Formatting",
        description: "Overly consistent code style, as if formatted by a tool.",
        weight: 4,
        detected: false,
      },
      {
        name: "External AI References",
        description: "Links or references to AI docs, OpenAI, Anthropic, v0.dev, etc., in code or docs.",
        weight: 6,
        detected: false,
      },
      {
        name: "Build/CI AI Artifacts",
        description: "Workflow files referencing AI build steps or model deployments.",
        weight: 5,
        detected: false,
      }
    );

  const html = doc.documentElement.innerHTML;
  const bodyText = doc.body.innerText;

  // 1. Tailwind Density
  const allElements = doc.querySelectorAll('*');
  let classCount = 0;
  allElements.forEach(el => {
    if (el.className && typeof el.className === 'string') {
      classCount += el.className.split(' ').length;
    }
  });
  const density = classCount / (allElements.length || 1);
  factors[0].detected = density > 4.5 || html.includes('tw-');

  // 2. Shadcn & Radix
  const shadcnMarkers = ['bg-background', 'text-foreground', 'data-radix-', 'data-state=', 'rounded-xl', 'border-input'];
  factors[1].detected = shadcnMarkers.filter(m => html.includes(m)).length >= 3;

  // 3. Lucide & AI SVGs
  const hasLucide = html.includes('lucide') || !!doc.querySelector('svg[class*="lucide"]');
  factors[2].detected = hasLucide;

  // 4. Vibe Stack (Combination)
  const hasMotion = html.includes('framer-motion') || html.includes('motion-');
  factors[3].detected = hasMotion && (hasLucide || factors[0].detected);

  // 5. AI IDE & Agent Markers (Cursor, Windsurf, Trae, Replit, Devin)
  const ideMarkers = [
    'cursor-ignore',
    '__cursor',
    'windsurf',
    'trae-ide',
    'replit-code-editor',
    'devin-ai',
    'claude-code',
    'generated by cursor',
    'created with cursor',
    'ai-generated',
    'vibe-coding'
  ];
  const hasIDEMarker = ideMarkers.some(m => html.toLowerCase().includes(m));

  // Check for specific comment patterns often left by AI IDEs
  const comments = Array.from(doc.childNodes)
    .filter(node => node.nodeType === Node.COMMENT_NODE)
    .map(node => node.nodeValue?.toLowerCase() || '');
  const hasAIComment = comments.some(c =>
    c.includes('ai generated') ||
    c.includes('cursor') ||
    c.includes('vibe') ||
    c.includes('prompt:') ||
    c.includes('generated by')
  );

  factors[4].detected = hasIDEMarker || hasAIComment;

  // 6. Platform Signatures (AI Studio, Lovable, v0, Bolt)
  const metaGenerator = doc.querySelector('meta[name="generator"]')?.getAttribute('content')?.toLowerCase() || '';
  const isAIStudio = html.includes('metadata.json') || html.includes('SPDX-License-Identifier: Apache-2.0');
  const isLovable = html.includes('lovable') || html.includes('gptengineer') || html.includes('lovable-project');
  const isBolt = html.includes('bolt-') || html.includes('stackblitz') || html.includes('bolt.new');
  const isV0 = html.includes('v0.dev') || metaGenerator.includes('v0');
  const isReplit = html.includes('replit.app') || html.includes('replit-agent') || html.includes('replit.com');
  const isVercelAI = html.includes('vercel-ai-sdk') || html.includes('ai.vercel.app');

  factors[5].detected = isAIStudio || isLovable || isBolt || isV0 || isReplit || isVercelAI;

  // Calculate score
  let totalScore = 0;
  factors.forEach(f => {
    if (f.detected) totalScore += f.weight;
  });

  // High confidence boosts
  if (isAIStudio || isV0 || isLovable || isReplit || hasIDEMarker) {
    totalScore = Math.max(90, totalScore);
  }

  return {
    score: Math.min(100, totalScore),
    factors,
  };
}


