/**
 * Content script — injected into every page by the extension.
 *
 * NOTE: This file cannot use ES module imports. The heuristic logic below
 * must stay in sync with src/lib/vibe-detector.ts, which is the single
 * source of truth for factor definitions and detection algorithms.
 * When updating heuristics, always update both files together.
 */

// ---------------------------------------------------------------------------
// Factor definitions (keep in sync with VIBE_FACTORS in vibe-detector.ts)
// ---------------------------------------------------------------------------
const FACTORS = [
  // --- Core factors ---
  { name: 'Tailwind & Utility DNA',    description: 'Massive utility class patterns typical of v0, Lovable, and Bolt.',         weight: 15 },
  { name: 'Shadcn/UI & Radix',         description: 'Radix component structures and standard Shadcn classes.',                   weight: 15 },
  { name: 'AI Iconography (Lucide)',   description: 'Heavy use of Lucide Icons, the AI industry standard.',                      weight: 10 },
  { name: 'Vibe Coding Stack',         description: 'Combined use of Framer Motion, Lucide, and Tailwind.',                      weight: 15 },
  { name: 'AI IDE & Agent Markers',    description: 'Signatures from Cursor, Windsurf, Trae, Replit, or Devin.',                 weight: 25 },
  { name: 'Platform Signatures',       description: 'Markers from Google AI Studio, Lovable, v0, or Bolt.new.',                  weight: 20 },
  // --- Advanced factors ---
  { name: 'Prompt Artifact Comments',  description: "Comments or metadata referencing prompts, e.g., 'Prompt: ...' or 'Generated by ...'", weight: 7 },
  { name: 'Model/Provider Metadata',   description: 'References to OpenAI, Anthropic, Google, or license headers auto-inserted by AI platforms.', weight: 7 },
  { name: 'Generic Code Structure',    description: 'Placeholder text or overly generic names like "Feature 1", "Lorem Ipsum", or "Bento Grid".', weight: 6 },
  { name: 'AI SDK/Dependency Clues',   description: 'Presence of AI SDKs or dependencies (e.g., openai, langchain, gpt-engineer).', weight: 6 },
  { name: 'Commit/PR Metadata',        description: 'Commit messages or PR descriptions referencing AI tools or prompt-based workflows.', weight: 5 },
  { name: 'Default AI UI Patterns',    description: 'Default layouts or icon sets popular with AI tools (e.g., Bento Grid, Tabler Icons).', weight: 5 },
  { name: 'Consistent Formatting',     description: 'Overly consistent code style, as if formatted by a tool across the entire codebase.', weight: 4 },
  { name: 'External AI References',    description: 'Links or references to AI docs, OpenAI, Anthropic, v0.dev, etc., in code or docs.', weight: 6 },
  { name: 'Build/CI AI Artifacts',     description: 'Workflow files referencing AI build steps or model deployments.',           weight: 5 },
];

// ---------------------------------------------------------------------------
// Detection logic (keep in sync with analyzeVibe() in vibe-detector.ts)
// ---------------------------------------------------------------------------
function analyzeVibe() {
  const factors = FACTORS.map((f) => ({ ...f, detected: false }));
  const html = document.documentElement?.innerHTML ?? '';

  // 1. Tailwind density
  const allElements = document.querySelectorAll('*');
  let classCount = 0;
  allElements.forEach((el) => {
    if (typeof el.className === 'string' && el.className.trim()) {
      classCount += el.className.trim().split(/\s+/).length;
    }
  });
  factors[0].detected = classCount / (allElements.length || 1) > 4.5 || html.includes('tw-');

  // 2. Shadcn / Radix
  const shadcnMarkers = ['bg-background', 'text-foreground', 'data-radix-', 'data-state=', 'rounded-xl', 'border-input'];
  factors[1].detected = shadcnMarkers.filter((m) => html.includes(m)).length >= 3;

  // 3. Lucide icons
  const hasLucide = html.includes('lucide') || !!document.querySelector('svg[class*="lucide"]');
  factors[2].detected = hasLucide;

  // 4. Vibe stack combination
  const hasMotion = html.includes('framer-motion') || html.includes('motion-');
  factors[3].detected = hasMotion && (hasLucide || factors[0].detected);

  // 5. AI IDE & agent markers
  const ideMarkers = [
    'cursor-ignore', '__cursor', 'windsurf', 'trae-ide',
    'replit-agent', 'devin-ai', 'claude-code',
    'generated by cursor', 'created with cursor',
  ];
  const hasIDEMarker = ideMarkers.some((m) => html.toLowerCase().includes(m));
  const comments = [];
  (function collectComments(node) {
    if (node.nodeType === Node.COMMENT_NODE) comments.push((node.nodeValue ?? '').toLowerCase());
    node.childNodes.forEach(collectComments);
  })(document);
  const hasAIComment = comments.some((c) =>
    c.includes('ai generated') || c.includes('cursor') || c.includes('vibe') ||
    c.includes('prompt:') || c.includes('generated by'),
  );
  factors[4].detected = hasIDEMarker || hasAIComment;

  // 6. Platform signatures
  const metaGenerator = document.querySelector('meta[name="generator"]')?.getAttribute('content')?.toLowerCase() ?? '';
  const isAIStudio = html.includes('metadata.json') || html.includes('SPDX-License-Identifier: Apache-2.0');
  const isLovable = html.includes('lovable') || html.includes('gptengineer') || html.includes('lovable-project');
  const isBolt = html.includes('bolt-') || html.includes('stackblitz') || html.includes('bolt.new');
  const isV0 = html.includes('v0.dev') || metaGenerator.includes('v0');
  const isReplit = html.includes('replit.app') || html.includes('replit-agent') || html.includes('replit.com');
  const isVercelAI = html.includes('vercel-ai-sdk') || html.includes('ai.vercel.app');
  factors[5].detected = isAIStudio || isLovable || isBolt || isV0 || isReplit || isVercelAI;

  // 7. Prompt artifact comments (already captured in hasAIComment above)
  factors[6].detected = hasAIComment;

  // 8. Model/Provider metadata
  const providerMarkers = ['openai', 'anthropic', 'gemini', 'claude', 'gpt-4', 'llama', 'spdx-license-identifier'];
  factors[7].detected = providerMarkers.some((m) => html.toLowerCase().includes(m));

  // 9. Generic code structure — placeholder text typical of AI scaffolding
  const placeholderText = ['feature 1', 'feature 2', 'feature 3', 'lorem ipsum', 'bento grid', 'card title', 'card description'];
  factors[8].detected = placeholderText.some((t) => (document.body?.innerText ?? '').toLowerCase().includes(t));

  // 10. AI SDK / dependency clues
  const sdkMarkers = ['openai', 'langchain', 'gpt-engineer', 'vercel/ai', '@ai-sdk', 'huggingface'];
  factors[9].detected = sdkMarkers.some((m) => html.toLowerCase().includes(m));

  // 11. Commit/PR metadata — can't be detected from DOM, always false
  factors[10].detected = false;

  // 12. Default AI UI patterns — Tabler icons, Bento layouts
  factors[11].detected = html.includes('tabler-icon') || html.includes('bento') || html.includes('heroicon');

  // 13. Consistent formatting — can't be reliably detected from DOM, always false
  factors[12].detected = false;

  // 14. External AI references
  const externalAIRefs = ['openai.com', 'anthropic.com', 'v0.dev', 'claude.ai', 'chat.openai.com'];
  factors[13].detected = externalAIRefs.some((m) => html.includes(m));

  // 15. Build/CI AI artifacts — can't be detected from DOM, always false
  factors[14].detected = false;

  // Score
  let totalScore = factors.reduce((sum, f) => sum + (f.detected ? f.weight : 0), 0);
  if (isAIStudio || isV0 || isLovable || isReplit || hasIDEMarker) totalScore = Math.max(90, totalScore);

  return { score: Math.min(100, totalScore), factors };
}

// ---------------------------------------------------------------------------
// Message listener — popup sends { action: 'analyze' } to get a VibeResult
// ---------------------------------------------------------------------------
chrome.runtime.onMessage.addListener((request, _sender, sendResponse) => {
  if (request.action === 'analyze') {
    sendResponse(analyzeVibe());
  }
  return true;
});
