/**
 * Content Script for VibeCheck
 * Runs in the context of the web page.
 */

function analyzeVibe() {
  const factors = [
    { name: "Tailwind & Utility DNA", weight: 12, detected: false },
    { name: "Shadcn/UI & Radix", weight: 10, detected: false },
    { name: "AI Iconography (Lucide)", weight: 8, detected: false },
    { name: "Vibe Coding Stack", weight: 10, detected: false },
    { name: "AI IDE & Agent Markers", weight: 18, detected: false },
    { name: "Platform Signatures", weight: 15, detected: false },
    // Advanced heuristics
    { name: "Prompt Artifact Comments", weight: 7, detected: false },
    { name: "Model/Provider Metadata", weight: 7, detected: false },
    { name: "Generic Code Structure", weight: 6, detected: false },
    { name: "AI SDK/Dependency Clues", weight: 6, detected: false },
    { name: "Commit/PR Metadata", weight: 5, detected: false },
    { name: "Default AI UI Patterns", weight: 5, detected: false },
    { name: "English-Only Comments", weight: 4, detected: false },
    { name: "Consistent Formatting", weight: 4, detected: false },
    { name: "External AI References", weight: 6, detected: false },
    { name: "Build/CI AI Artifacts", weight: 5, detected: false },
    // Multilanguage/framework heuristics
    { name: "Python/Django AI Patterns", weight: 6, detected: false },
    { name: "Java/Spring AI Patterns", weight: 6, detected: false },
    { name: "PHP/Laravel AI Patterns", weight: 6, detected: false },
  ];
  // --- Multilanguage/framework heuristics ---
  // Python/Django
  const pyDjangoPatterns = [
    '# generated by chatgpt', '# generated by copilot', '# ai generated',
    'def handler', 'def my_view', 'ai_generated.py', 'from django', 'class MyModel',
    '"""Generated by', '"""AI', 'ai-generated', 'prompt:', 'gpt_output', 'autogen'
  ];
  const hasPyDjango = pyDjangoPatterns.some(p => html.toLowerCase().includes(p) || bodyText.toLowerCase().includes(p));
  factors[16].detected = hasPyDjango;

  // Java/Spring
  const javaSpringPatterns = [
    '// Generated by Copilot', '// AI generated', 'public class MyService', 'MyController',
    '@RestController', '@Autowired', 'Generated by GPT', 'ai commit', 'initial commit by ai',
    'copilot', 'gpt-4', 'ai-generated', 'prompt:'
  ];
  const hasJavaSpring = javaSpringPatterns.some(p => html.toLowerCase().includes(p) || bodyText.toLowerCase().includes(p));
  factors[17].detected = hasJavaSpring;

  // PHP/Laravel
  const phpLaravelPatterns = [
    '// Generated by Copilot', '// AI generated', 'class MyController', 'public function handle',
    'ai_generated.php', 'use Illuminate', 'migration', 'Seeder', 'prompt:', 'gptengineer', 'ai-generated'
  ];
  const hasPHPLaravel = phpLaravelPatterns.some(p => html.toLowerCase().includes(p) || bodyText.toLowerCase().includes(p));
  factors[18].detected = hasPHPLaravel;

  const html = document.documentElement.innerHTML;
  const bodyText = document.body.innerText;

  // 1. Tailwind Density
  const allElements = document.querySelectorAll('*');
  let classCount = 0;
  allElements.forEach(el => {
    if (el.className && typeof el.className === 'string') {
      classCount += el.className.split(' ').length;
    }
  });
  const density = classCount / (allElements.length || 1);
  factors[0].detected = density > 4.5 || html.includes('tw-');

  // 2. Shadcn & Radix
  const shadcnMarkers = ['bg-background', 'text-foreground', 'data-radix-', 'data-state=', 'rounded-xl', 'border-input'];
  factors[1].detected = shadcnMarkers.filter(m => html.includes(m)).length >= 3;

  // 3. Lucide & AI SVGs
  const hasLucide = html.includes('lucide') || !!document.querySelector('svg[class*="lucide"]');
  factors[2].detected = hasLucide;

  // 4. Vibe Stack (Combination)
  const hasMotion = html.includes('framer-motion') || html.includes('motion-');
  factors[3].detected = hasMotion && (hasLucide || factors[0].detected);

  // 5. AI IDE & Agent Markers
  const ideMarkers = [
    'cursor-ignore', '__cursor', 'windsurf', 'trae-ide', 'replit-code-editor',
    'devin-ai', 'claude-code', 'generated by cursor', 'created with cursor',
    'ai-generated', 'vibe-coding'
  ];
  const hasIDEMarker = ideMarkers.some(m => html.toLowerCase().includes(m));

  // Check for specific comment patterns often left by AI IDEs
  const comments = [];
  (function collectComments(node) {
    if (!node) return;
    if (node.nodeType === Node.COMMENT_NODE) comments.push((node.nodeValue || '').toLowerCase());
    if (node.childNodes) Array.from(node.childNodes).forEach(collectComments);
  })(document);
  const hasAIComment = comments.some(c =>
    c.includes('ai generated') ||
    c.includes('cursor') ||
    c.includes('vibe') ||
    c.includes('prompt:') ||
    c.includes('generated by')
  );
  factors[4].detected = hasIDEMarker || hasAIComment;

  // 6. Platform Signatures
  const metaGenerator = document.querySelector('meta[name="generator"]')?.getAttribute('content')?.toLowerCase() || '';
  const isAIStudio = html.includes('metadata.json') || html.includes('SPDX-License-Identifier: Apache-2.0');
  const isLovable = html.includes('lovable') || html.includes('gptengineer') || html.includes('lovable-project');
  const isBolt = document.location.hostname.includes('bolt.new') || html.includes('bolt.new') || html.includes('stackblitz');
  const isV0 = html.includes('v0.dev') || metaGenerator.includes('v0');
  const isReplit = html.includes('replit.app') || html.includes('replit-agent') || html.includes('replit.com');
  const isVercelAI = html.includes('vercel-ai-sdk') || html.includes('ai.vercel.app');
  factors[5].detected = isAIStudio || isLovable || isBolt || isV0 || isReplit || isVercelAI;

  // 7. Prompt Artifact Comments
  const promptComment = comments.some(c => c.includes('prompt:') || c.includes('prompt used:') || c.includes('generated by') || c.includes('prompt-injection'));
  factors[6].detected = promptComment;

  // 8. Model/Provider Metadata
  const providerRefs = [
    'openai', 'anthropic', 'google ai', 'vertexai', 'gpt-4', 'gpt-3', 'claude', 'llama',
    'spdx-license-identifier', 'apache-2.0', 'ai21', 'cohere', 'mistral', 'gemini', 'groq'
  ];
  const hasProviderMeta = providerRefs.some(ref => html.toLowerCase().includes(ref));
  factors[7].detected = hasProviderMeta;

  // 9. Generic Code Structure
  const genericNames = ['doSomething', 'myFunction', 'handler1', 'feature 1', 'lorem ipsum', 'bento grid', 'autogen', 'gpt_output', 'ai-generated'];
  const hasGenericStructure = genericNames.some(n => html.toLowerCase().includes(n) || bodyText.toLowerCase().includes(n));
  factors[8].detected = hasGenericStructure;

  // 10. AI SDK/Dependency Clues (from script tags or window vars)
  const sdkRefs = ['openai', 'langchain', 'gpt-engineer', 'anthropic', 'vercel-ai-sdk'];
  const scripts = Array.from(document.querySelectorAll('script')).map(s => (s.src || '') + (s.innerHTML || '')).join(' ').toLowerCase();
  const hasSDK = sdkRefs.some(sdk => scripts.includes(sdk));
  factors[9].detected = hasSDK;

  // 11. Commit/PR Metadata (look for commit/PR clues in comments)
  const commitClues = ['generated by gpt', 'ai commit', 'initial commit by ai', 'copilot', 'gpt-4'];
  const hasCommitClue = comments.some(c => commitClues.some(clue => c.includes(clue)));
  factors[10].detected = hasCommitClue;

  // 12. Default AI UI Patterns
  const aiUIPatterns = ['bento grid', 'feature card', 'hero section', 'lucide', 'tabler', 'feather'];
  const hasAIPattern = aiUIPatterns.some(p => html.toLowerCase().includes(p));
  factors[11].detected = hasAIPattern;

  // 13. English-Only Comments (if all comments are English, and doc lang is not en)
  const docLang = document.documentElement.lang || '';
  const isNonEnglishDoc = docLang && docLang !== 'en';
  const allCommentsEnglish = comments.length > 0 && comments.every(c => /^[\x00-\x7F\s.,:;!?"'()\[\]{}<>\-_/\\]+$/.test(c));
  factors[12].detected = isNonEnglishDoc && allCommentsEnglish;

  // 14. Consistent Formatting (if all lines end with LF and indentation is consistent)
  // This is a weak heuristic, so we just check for lots of LF and 2-space indents in HTML
  const lfCount = (html.match(/\n/g) || []).length;
  const twoSpaceCount = (html.match(/\n  /g) || []).length;
  factors[13].detected = lfCount > 50 && twoSpaceCount > 30;

  // 15. External AI References
  const aiLinks = ['openai.com', 'anthropic.com', 'v0.dev', 'cursor.so', 'gptengineer', 'replit.com', 'stackblitz.com'];
  const hasAILink = aiLinks.some(link => html.toLowerCase().includes(link));
  factors[14].detected = hasAILink;

  // 16. Build/CI AI Artifacts (look for workflow/ci/cd references in HTML)
  const ciRefs = ['github actions', 'ci/cd', 'ai build', 'model deployment', 'vercel', 'cloud run'];
  const hasCI = ciRefs.some(ref => html.toLowerCase().includes(ref));
  factors[15].detected = hasCI;

  let score = 0;
  factors.forEach(f => { if (f.detected) score += f.weight; });
  if (isAIStudio || isV0 || isLovable || isReplit || hasIDEMarker) score = Math.max(90, score);

  return { score: Math.min(100, score), factors };
}

// Listen for messages from the popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "analyze") {
    sendResponse(analyzeVibe());
  }
  return true;
});
